AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  DadosEntradaBucket: 
    Type: AWS::S3::Bucket 
    Properties: 
      BucketName: !Sub "dadosentrada-797225460896-us-east-1"

  DadosSaidaBucket: 
    Type: AWS::S3::Bucket 
    Properties: 
      BucketName: "dadossaida-797225460896-us-east-1"     

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies: 
        - PolicyName: S3AccessPolicy
          PolicyDocument: 
            Version: "2012-10-17" 
            Statement: 
              - Effect: Allow 
                Action: 
                  - s3:ListBucket 
                  - s3:GetObject 
                  - s3:PutObject 
                Resource: 
                  - !Sub arn:aws:s3:::${DadosEntradaBucket} 
                  - !Sub arn:aws:s3:::${DadosEntradaBucket}/* 
                  - !Sub arn:aws:s3:::${DadosSaidaBucket} 
                  - !Sub arn:aws:s3:::${DadosSaidaBucket}/*

  ProcessamentoDadosTCC:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: processamentodadostcc
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      MemorySize: 256
      Timeout: 60
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        DailyTrigger:
          Type: Schedule
          Properties:
            Schedule: cron(0 9 * * ? *)   # 09:00 UTC = 06:00 BRT
