name: Deploy AWS Lambda with EventBridge

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Limpar build antigo
        run: rm -rf .aws-sam/build

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build SAM
        run: sam build

      - name: Deploy com SAM
        run: |
          sam deploy \
            --template-file template.yaml \
            --stack-name processamentodadostcc-stack \
            --capabilities CAPABILITY_IAM \
            --region us-east-1 \
            --resolve-s3 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
